//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from nores.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="noresParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface InoresListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] noresParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] noresParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] noresParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] noresParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign_stmt([NotNull] noresParser.Assign_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign_stmt([NotNull] noresParser.Assign_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] noresParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] noresParser.ReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] noresParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] noresParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.arguments_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments_list([NotNull] noresParser.Arguments_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.arguments_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments_list([NotNull] noresParser.Arguments_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.basic_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasic_reference([NotNull] noresParser.Basic_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.basic_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasic_reference([NotNull] noresParser.Basic_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.structure_qualification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructure_qualification([NotNull] noresParser.Structure_qualificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.structure_qualification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructure_qualification([NotNull] noresParser.Structure_qualificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.structure_qualification_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructure_qualification_list([NotNull] noresParser.Structure_qualification_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.structure_qualification_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructure_qualification_list([NotNull] noresParser.Structure_qualification_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript([NotNull] noresParser.SubscriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript([NotNull] noresParser.SubscriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.subscript_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript_commalist([NotNull] noresParser.Subscript_commalistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.subscript_commalist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript_commalist([NotNull] noresParser.Subscript_commalistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] noresParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] noresParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_9([NotNull] noresParser.Expression_9Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_9"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_9([NotNull] noresParser.Expression_9Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_8([NotNull] noresParser.Expression_8Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_8"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_8([NotNull] noresParser.Expression_8Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_7([NotNull] noresParser.Expression_7Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_7"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_7([NotNull] noresParser.Expression_7Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_6([NotNull] noresParser.Expression_6Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_6"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_6([NotNull] noresParser.Expression_6Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_5([NotNull] noresParser.Expression_5Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_5([NotNull] noresParser.Expression_5Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_4([NotNull] noresParser.Expression_4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_4([NotNull] noresParser.Expression_4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_3([NotNull] noresParser.Expression_3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_3([NotNull] noresParser.Expression_3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_2([NotNull] noresParser.Expression_2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_2([NotNull] noresParser.Expression_2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.expression_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_1([NotNull] noresParser.Expression_1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.expression_1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_1([NotNull] noresParser.Expression_1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.prefix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefix_expression([NotNull] noresParser.Prefix_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.prefix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefix_expression([NotNull] noresParser.Prefix_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.parenthesized_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesized_expression([NotNull] noresParser.Parenthesized_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.parenthesized_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesized_expression([NotNull] noresParser.Parenthesized_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.primitive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitive_expression([NotNull] noresParser.Primitive_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.primitive_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitive_expression([NotNull] noresParser.Primitive_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] noresParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] noresParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.prefix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefix_operator([NotNull] noresParser.Prefix_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.prefix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefix_operator([NotNull] noresParser.Prefix_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_operator([NotNull] noresParser.Comparison_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.comparison_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_operator([NotNull] noresParser.Comparison_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] noresParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] noresParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] noresParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] noresParser.KeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.keyword_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword_stmt([NotNull] noresParser.Keyword_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.keyword_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword_stmt([NotNull] noresParser.Keyword_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_stmt([NotNull] noresParser.Call_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.call_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_stmt([NotNull] noresParser.Call_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.goto_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoto_stmt([NotNull] noresParser.Goto_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.goto_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoto_stmt([NotNull] noresParser.Goto_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.end_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnd_stmt([NotNull] noresParser.End_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.end_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnd_stmt([NotNull] noresParser.End_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="noresParser.procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_stmt([NotNull] noresParser.Procedure_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="noresParser.procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_stmt([NotNull] noresParser.Procedure_stmtContext context);
}
