namespace Steadsoft.Novus.Scanner.Enums
{

    // Consider moving these to a text file and then creating per-language variants...

    public enum Keywords
    {
        IsNotAKeyword = 0,
        Aligned,
        Argument,
        Binary,
        Builtin,
        By,
        Bypass,                 // A field type in a struct that's catered for in the layout but never accessed by code.
        Call,
        Coroutine,
        Decimal,
        Declare,
        Define,
        End,
        Enum,
        Fixed,
        Float,
        Function,
        Goto,
        Internal,
        Interrupt,
        Language,
        Loop,
        Namespace,
        Offset,
        Out,
        Padding,
        Pointer,
        Private,
        Procedure,
        Public,
        Readonly,
        Ref,
        Return,
        Returnon,
        Singlet,
        Static,
        String,
        Structure,
        To,
        Type,
        Unaigned,
        Until,
        Using,
        While,
        Varying,
        Yield,
        Arg = Argument + AbbreviationShift,
        Bin = Binary + AbbreviationShift,
        Dcl = Declare + AbbreviationShift,
        Dec = Decimal + AbbreviationShift,
        Def = Define + AbbreviationShift,
        Func = Function + AbbreviationShift,
        Pad = Padding+ AbbreviationShift,
        Proc = Procedure + AbbreviationShift,
        Ptr = Pointer+ AbbreviationShift,
        Struct = Structure + AbbreviationShift,
        AbbreviationShift = 1000
 }
}
